# Generated by Django 4.2.8 on 2023-12-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_alter_order_options_alter_order_adult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adult',
        ),
    ]
